# Generated by Django 4.2.1 on 2023-06-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="content",
            field=models.TextField(default="Default Content"),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversation.conversation",
            ),
        ),
    ]
